### ISSUE TITLE
Guide Actions don't work

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#445]
![screenshot 2015-01-20 09 07 27](https://cloud.githubusercontent.com/assets/485583/5811120/f5b9be14-a083-11e4-903e-1aa5230c8dfd.png)

This is the error in the console:

```
Error: [$injector:unpr] http://errors.angularjs.org/1.3.0-beta.19/$injector/unpr?p0=tProvider%20%3C-%20t%20%3C-%20autoFocusDirective
    at Error (native)
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:5203
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:20061
    at Object.i [as get] (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:19078)
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:20134
    at i (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:19078)
    at Object.r [as invoke] (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:19336)
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:24232
    at a (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:5585)
    at Object.<anonymous> (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:4:24199)
```

**Comment by simonv3** [comment]
Already exists #437
