### ISSUE TITLE
Images aren't showing in the stages section of guides.

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#450]
Error message in console is:

```
TypeError: Cannot read property 'forEach' of null
    at e.setCurrentUser (https://openfarm.cc/assets/guides/show-4e5a23edd22e8158772b602128a8cb11.js:1:470)
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:8:30680
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:6402
    at https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:20124
    at c.$eval (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:27068)
    at c.$digest (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:25617)
    at c.$apply (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:27398)
    at l (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:6643)
    at v (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:8973)
    at XMLHttpRequest.w.onreadystatechange (https://openfarm.cc/assets/application-595ed91375cc633c4e2b7bf6e61a71ab.js:5:9566)
```

**Comment by warpling** [comment]
My bad, I temporarily removed them. Working on re-adding them now.

**Comment by simonv3** [comment]
Also have a look at my latest PR. I fixed the action items thing (by just copying the code into the specific `new-guide` css).
