### ISSUE TITLE
undefined method `encrypted_password=' on rake db:setup

### ISSUE THREAD

**Issue by dedesite** [openfarmcc/OpenFarm#542]
Hi,

I started a fresh install of OpenFarm and everything seems fine except that I can't run rake db:setup without errors.

I ran this in rails console, so it seems ok, any advice ?
```
User.new.respond_to?(:encrypted_password=)
=> true
```

Here is the full backtrace :
```
** Invoke db:setup (first_time)
** Invoke db:create (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:create
** Invoke db:mongoid:create_indexes (first_time)
** Invoke environment 
** Invoke db:mongoid:load_models (first_time)
** Execute db:mongoid:load_models
** Execute db:mongoid:create_indexes
I, [2015-03-12T20:51:34.147768 #27813]  INFO -- : MONGOID: Created indexes on Delayed::Backend::Mongoid::Job:
I, [2015-03-12T20:51:34.147833 #27813]  INFO -- : MONGOID: Index: {:locked_by=>-1, :priority=>1, :run_at=>1}, Options: {}
I, [2015-03-12T20:51:34.148980 #27813]  INFO -- : MONGOID: Created indexes on Crop:
I, [2015-03-12T20:51:34.149026 #27813]  INFO -- : MONGOID: Index: {:_slugs=>1}, Options: {:unique=>true, :sparse=>true}
I, [2015-03-12T20:51:34.149809 #27813]  INFO -- : MONGOID: Created indexes on Guide:
I, [2015-03-12T20:51:34.149854 #27813]  INFO -- : MONGOID: Index: {:_slugs=>1}, Options: {:unique=>true, :sparse=>true}
I, [2015-03-12T20:51:34.150880 #27813]  INFO -- : MONGOID: Created indexes on StageOption:
I, [2015-03-12T20:51:34.150931 #27813]  INFO -- : MONGOID: Index: {:_slugs=>1}, Options: {:unique=>true, :sparse=>true}
** Invoke db:seed (first_time)
** Invoke environment 
** Execute db:seed
rake aborted!
NoMethodError: undefined method `encrypted_password=' for #<User:0x00000002138a38>
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/devise-3.4.1/lib/devise/models/database_authenticatable.rb:42:in `password='
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `public_send'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:12:in `object'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/notifications.rb:161:in `instrument'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/home/dede/Projects/OpenFarm/db/seeds.rb:4:in `<top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/dede/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/dede/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/rake:23:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/rake:23:in `<main>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/ruby_executable_hooks:15:in `eval'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:seed
```

**Comment by simonv3** [comment]
Hey @dedesite, this is weird. 

From a quick look on SO, it looks like this is usually a problem when the database isn't set up right. 

http://stackoverflow.com/questions/22490699/get-nomethoderror-in-deviseregistrationscontrollercreate
http://stackoverflow.com/questions/15159355/ror-using-devise-encrypted-password

We don't usually use db:migrate, but maybe it's worth trying to run it?

Do things work outside of the seeds file?

**Comment by dedesite** [comment]
Hi,

I tried db:migrate but also got errors...
The site is running but when I try to acces user (registration for example), I got the same errors...

I've execute db:migrate without error but it change nothing.

My mongodb installation was not functionnal, I reinstall it, the service is now running but it doesn't fix anything.

I've investigate a bit more and it seems that the devise configuration is wrong (I never used this tool).
I manage to bypass the errors by adding : 

```field :password,           :type => String, :default => ""```

in models/user.rb

And remove temporarly ":database_authenticatable" in the devise module list.

I pass the user creation but now hangs on garden creation problem with Mongoid::Job :

```
** Execute db:seed
attribute=email
attribute=display_name
attribute=location
attribute=years_experience
attribute=password_confirmation
attribute=admin
attribute=password
attribute=is_private
attribute=name
attribute=description
attribute=location
attribute=type
attribute=soil_type
attribute=is_private
attribute=user
rake aborted!
NoMethodError: undefined method `handler=' for #<Delayed::Backend::Mongoid::Job:0x0000000643c050>
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:81:in `payload_object='
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:97:in `process_attribute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:25:in `block in process_attributes'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:23:in `each_pair'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:23:in `process_attributes'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/document.rb:110:in `block in initialize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/threaded/lifecycle.rb:84:in `_building'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/document.rb:104:in `initialize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:32:in `new'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:32:in `enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/message_sending.rb:12:in `method_missing'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/queue_adapters/delayed_job_adapter.rb:8:in `enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/enqueuing.rb:69:in `block in enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:384:in `block in _run__1063740812956416327__enqueue__callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:31:in `call'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:31:in `block (3 levels) in <module:Logging>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61:in `block in tag_logger'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61:in `tag_logger'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:30:in `block (2 levels) in <module:Logging>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_68'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:373:in `_run__1063740812956416327__enqueue__callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/enqueuing.rb:65:in `enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/enqueuing.rb:16:in `perform_later'
/home/dede/Projects/OpenFarm/app/models/garden.rb:30:in `reindex_guides'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:379:in `_run__2676917379317113181__save__callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/creatable.rb:115:in `prepare_insert'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/creatable.rb:23:in `insert'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/savable.rb:23:in `save'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/savable.rb:44:in `save!'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/notifications.rb:161:in `instrument'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/home/dede/Projects/OpenFarm/db/seeds.rb:9:in `<top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/dede/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/rake:23:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/rake:23:in `<main>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/ruby_executable_hooks:15:in `eval'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
```

I never used MongoDb, nor Devise so I can't be much more help. I'll continue investigation.

Thanks,
Andréas

**Comment by simonv3** [comment]
Thanks Andréas.

You shouldn't need to change the password, we don't want it to store a default - it should never be blank! Similarly, don't want to remove anything from devise - as that's the gem that manages user authentication.

Looks like the problem you're encountering after that has to do with the reindex that happens after user creation. 

I've changed some things about user authentication in the latest PR actually, so maybe try pulling that down?

**Comment by dedesite** [comment]
Hi,

I know that I shouldn't add default password or remove the authentication, but was trying that to see if it goes further and maybe understand what is going on...

I tried with your new code but still got the same errors.

Is there a specific MongoDB configuration to do ? How can I test that MongoDB is working ?
```sudo service mongod status```
Tell me that 
```mongod start/running, process 1116```

So I guess it's ok ?

Hope we'll find a solution soon.
Thanks for your help anyway.

**Comment by warpling** [comment]
@dedesite are you just trying to get MongoDB up and running? I usually just run `mongod -dbpath db` in the OpenFarm directory (assuming a `db/` directory has been created.

**Comment by dedesite** [comment]
I just wanted to check if this wasn't a MongoDB configuration/installation problem. MongoDB seems to be well configured but I never used this DB so I may be doing something wrong.
I have Ubuntu 14.04 and install MongoDB through the ppa mongodb-org as pointed out on the OpenFarm wiki.

**Comment by warpling** [comment]
Having the same issue when I run `rake db:reset` now :/ It's been awhile since I've messed with my local database…

**Comment by dedesite** [comment]
I've submit a fix for this issue. Now I have another bug... I'll open a new issue.

**Comment by md5** [comment]
Is it possible the issue is that `encrypted_password` is not defined as a field in the `factory_girl` setup here: https://github.com/openfarmcc/OpenFarm/blob/master/test/factories/users.rb

**Comment by dedesite** [comment]
I did a fresh install of the project today and I don't have anymore the bug, so you can close everything related to it :).
