### ISSUE TITLE
undefined method `handler=' for #<Delayed::Backend::Mongoid::Job on rake db:seed

### ISSUE THREAD

**Issue by dedesite** [openfarmcc/OpenFarm#572]
Hi,

I've got a new issue trying to seed the project.

Here is the full backtrace :

```
** Invoke db:seed (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:seed
rake aborted!
NoMethodError: undefined method `handler=' for #<Delayed::Backend::Mongoid::Job:0x00000006cb0b78>
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:81:in `payload_object='
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:97:in `process_attribute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:25:in `block in process_attributes'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:23:in `each_pair'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/attributes/processing.rb:23:in `process_attributes'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/document.rb:110:in `block in initialize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/threaded/lifecycle.rb:84:in `_building'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/document.rb:104:in `initialize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:32:in `new'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:32:in `enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/delayed_job-4.0.6/lib/delayed/message_sending.rb:12:in `method_missing'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/queue_adapters/delayed_job_adapter.rb:8:in `enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/enqueuing.rb:69:in `block in enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:384:in `block in _run__4162299375719841218__enqueue__callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:31:in `call'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:31:in `block (3 levels) in <module:Logging>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61:in `block in tag_logger'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `block in tagged'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:25:in `tagged'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/tagged_logging.rb:67:in `tagged'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:61:in `tag_logger'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/logging.rb:30:in `block (2 levels) in <module:Logging>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:211:in `_conditional_callback_around_69'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:373:in `_run__4162299375719841218__enqueue__callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/enqueuing.rb:65:in `enqueue'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activejob_backport-0.0.3/lib/active_job/enqueuing.rb:16:in `perform_later'
/home/dede/Projects/OpenFarm/app/models/garden.rb:30:in `reindex_guides'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:379:in `_run__2912490118111438459__save__callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/callbacks.rb:80:in `run_callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/creatable.rb:115:in `prepare_insert'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/creatable.rb:23:in `insert'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/savable.rb:23:in `save'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/persistable/savable.rb:44:in `save!'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `[]'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:15:in `create'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `tap'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/notifications.rb:161:in `instrument'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/home/dede/Projects/OpenFarm/db/seeds.rb:9:in `<top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `block in load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214:in `load_dependency'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:223:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bundler/gems/mongoid-8ce1c48118a0/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/dede/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/rake:23:in `load'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/rake:23:in `<main>'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/ruby_executable_hooks:15:in `eval'
/home/dede/.rvm/gems/ruby-2.2.0-preview1@openfarm/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed
```

Is anyone else having errors with ActiveJob ?

**Comment by warpling** [comment]
@simonv3, do you think going the Docker route might help with this?

**Comment by simonv3** [comment]
It should. I think these are the same brand of errors as the other issue, ie, to do with how mongodb is installed, and running alongside mongoid.

**Comment by md5** [comment]
I see `factory_girl` in this stack trace too...

**Comment by simonv3** [comment]
@md5 Isn't that because it's within a FactoryGirl call (in seeds.rb?)? @warpling maybe it's worth trying what Mike suggests in the PR. #571

**Comment by md5** [comment]
@simonv3 indeed! Should have looked closer at that before commenting...

It looks like `handler` is another thing that should be defined by a Mongoid `field` declaration: https://github.com/collectiveidea/delayed_job_mongoid/blob/5fe9d249d45d735564d26d8fba41f04b123995c7/lib/delayed/backend/mongoid.rb#L15

I guess it's possible this is related to how MongoDB is installed, but I don't think it's the same situation as the SO threads linked from #542. In those cases, ActiveRecord was involved, which means that the DB has to actually have the columns for the fields to get accessors. In the Mongoid case (as I'm sure you know), you need to declare fields/accessors with `field`, so I don't think it can be the same issue.

**Comment by md5** [comment]
Another thing to try might be for someone who is able to reproduce this to go through with a `pry` or something.

**Comment by dedesite** [comment]
I did a fresh install of the project today and I don't have anymore the bug, so you can close everything related to it :).
