### ISSUE TITLE
Something Funky With Impressions

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#585]
```
A TypeError occurred in crops#show:

  String can’t be coerced into Fixnum
  app/controllers/crops_controller.rb:15:in `show’


———————————————
Request:
———————————————

  * URL        : https://openfarm.cc/crops/54afdf033166630002ae0900
  * HTTP Method: GET
  * IP address :
  * Parameters : {“action”=>”show”, “controller”=>”crops”, “id”=>”54afdf033166630002ae0900”}
```

Only with brussels sprouts though.

**Comment by simonv3** [comment]
Still happening, 

```

A TypeError occurred in crops#show:

  String can't be coerced into Fixnum
  app/controllers/crops_controller.rb:15:in `show'


-------------------------------
Request:
-------------------------------

  * URL        : https://openfarm.cc/en/crops/brussels-sprouts
  * HTTP Method: GET
  * IP address : 115.98.115.151
  * Parameters : {"action"=>"show", "controller"=>"crops", "locale"=>"en", "id"=>"brussels-sprouts"}
  * Timestamp  : 2015-07-21 12:44:21 UTC
  * Server : b97ea558-13d7-45df-8f1c-9010ed8f0cf1
  * Rails root : /app
  * Process: 3
```

**Comment by simonv3** [comment]
The Impression for Brussels Sprouts (id: 54afdf033166630002ae0900) had somehow been changed to a string (probably through editing in the backend admin dashboard). This is now forced to be an integer in 8108b2bdeb146e8e4a7b72519365a9527bdca8bb, and has been properly changed for brussels sprouts as well.

**Comment by simonv3** [comment]
Had to do something similar for Guides.
