### ISSUE TITLE
Faraday::TimeoutError

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#602]
Just logging this in case anyone has any input. I suspect that it's just a hanging connection - I'm not quite sure what could have caused it.

```
A Faraday::TimeoutError occurred in crop_searches#search:

  Operation timed out after 10000 milliseconds with 0 bytes received
  app/controllers/crop_searches_controller.rb:6:in `search’


———————————————
Request:
———————————————

  * URL        : https://openfarm.cc/en/crop_search?q=summer+savory
  * HTTP Method: GET
  * IP address : 142.217.57.248
  * Parameters : {“q”=>”summer savory”, “controller”=>”crop_searches”, “action”=>”search”, “locale”=>”en”}
  * Timestamp  : 2015-04-14 20:50:16 UTC
  * Server : 5dfed6d0-742b-43f1-92b7-a039f0af383f
  * Rails root : /app
  * Process: 3
```

**Comment by md5** [comment]
Do you guys have logging turned on for Elasticsearch? You might get something useful out of the slow log: http://www.elastic.co/guide/en/elasticsearch/reference/1.5/index-modules-slowlog.html

**Comment by simonv3** [comment]
Hey Mike, sorry for leaving you hanging like that. I'll have a look at doing this later in the week. The error has been happening on and off since I posted it, so it's definitely not a one off.

**Comment by simonv3** [comment]
Just wanted to say that this hasn't gone away - it's still happening periodically: 

```
A Faraday::TimeoutError occurred in crops#index:

  Operation timed out after 10000 milliseconds with 0 bytes received
  app/controllers/api/crops_controller.rb:7:in `index'


-------------------------------
Request:
-------------------------------

  * URL        : https://openfarm.cc/api/crops?query=Chi
  * HTTP Method: GET
  * IP address : 203.121.21.10
  * Parameters : {"query"=>"Chi", "format"=>"json", "action"=>"index", "controller"=>"api/crops"}
  * Timestamp  : 2015-07-23 05:52:36 UTC
  * Server : 0206dbb5-c91a-4db0-a37b-76561d428aa8
  * Rails root : /app
  * Process: 3
```

**Comment by simonv3** [comment]
And this is probably related: 

```
An ActionView::Template::Error occurred in crops#show:

  [503] {"error":"All nodes in cluster are unavailable. Please check status.bonsai.io or contact support@bonsai.io for assistance.","status":503}
  app/models/guide_search.rb:47:in `results'


-------------------------------
Request:
-------------------------------

  * URL        : https://openfarm.cc/en/crops/cherry-tomato
  * HTTP Method: GET
  * IP address : 122.177.73.71
  * Parameters : {"action"=>"show", "controller"=>"crops", "locale"=>"en", "id"=>"cherry-tomato"}
  * Timestamp  : 2015-07-23 06:17:43 UTC
  * Server : 0206dbb5-c91a-4db0-a37b-76561d428aa8
  * Rails root : /app
  * Process: 3
```

**Comment by simonv3** [comment]
I have stopped getting these. Going to assume fixed.
