### ISSUE TITLE
Failure on /guides/new

### ISSUE THREAD

**Issue by andru** [openfarmcc/OpenFarm#635]
Just went to create a guide but get this error at page load so the crop typeahead (I'm presuming it's one)  doesn't work, and the 'Choose crop to continue' button never un-disables.

```
Error: [$injector:unpr] http://errors.angularjs.org/1.3.0-beta.19/$injector/unpr?p0=tProvider%20%3C-%20t%20%3C-%20autoFocusDirective
    at Error (native)
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:3:25891
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:7958
    at Object.n [as get] (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:6975)
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:8031
    at n (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:6975)
    at Object.s [as invoke] (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:7233)
    at https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:12129
    at r (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:3:26273)
    at Object.<anonymous> (https://openfarm.cc/assets/application-aca79496e6ca574a833bf1523ba469ec.js:4:12096)
```

**Comment by roryaronson** [comment]
Yep this one has been fixed in #608, but its not yet on production.
