### ISSUE TITLE
An ActionView::Template::Error occurred in crops#show:

### ISSUE THREAD

**Issue by simonv3** [openfarmcc/OpenFarm#697]
```
An ActionView::Template::Error occurred in crops#show:

  [503]
  app/models/guide_search.rb:47:in `results'


-------------------------------
Request:
-------------------------------

  * URL        : https://openfarm.cc/en/crops/strawberry
  * HTTP Method: GET
  * IP address : 94.188.11.73
  * Parameters : {"action"=>"show", "controller"=>"crops", "locale"=>"en", "id"=>"strawberry"}
...
-------------------------------
Backtrace:
-------------------------------

  app/models/guide_search.rb:47:in `results'
  app/models/guide_search.rb:52:in `method_missing'
  app/views/crops/show.html.erb:68:in `_app_views_crops_show_html_erb___2687984385713832355_70003271218500'
```

**Comment by TanSA05** [comment]
@simonv3 Is this issue solved?

**Comment by simonv3** [comment]
@TanSA05 I haven't seen it in a while, but it's not a clear "working vs not working" kind of bug. Sometimes it pops up for someone, but most of the time it doesn't happen. Let's ping again in a month. If it pops up again before that I'll post an update.

**Comment by TanSA05** [comment]
Okay.

**Comment by anyangocynthia** [comment]
@simonv3 we have tested this with @sigu and @stlmaris123 and it seems to be working fine we should close this
