### ISSUE TITLE
Test failures on first install against master

### ISSUE THREAD

**Issue by RickCarlino** [openfarmcc/OpenFarm#902]
Hi,

Just reinstalled the codebase after a long hiatus from the project.

 * I ran the "hard way" setup and am running on bare metal.
 * Elasticsearch and Mongo appear to be running.
 * I get numerous test failures, many relating to permissions.

Do I need to run indexing on Elasticsearch or anything like that? I already ran `rails db:setup`

```
Failures:

  1) UsersController should show all users on index if the current user is admin
     Failure/Error: expect(assigns(:users)).to match_array([public_user, user, private_user])
     
       expected collection contained:  [#<User _id: BSON::ObjectId('589cee7f72683d222a000012'), admin: true, agree: nil, created_at: Thu, 09...lse, level: 0, mailing_list: false, sash_id: nil, updated_at: Thu, 09 Feb 2017 22:34:40 UTC +00:00>]
       actual collection contained:    [#<User _id: BSON::ObjectId('589ce8e872683d1223000000'), admin: true, agree: nil, created_at: Thu, 09...lse, level: 0, mailing_list: false, sash_id: nil, updated_at: Thu, 09 Feb 2017 22:34:40 UTC +00:00>]
       the extra elements were:        [#<User _id: BSON::ObjectId('589ce8e872683d1223000000'), admin: true, agree: nil, created_at: Thu, 09...lse, level: 0, mailing_list: false, sash_id: nil, updated_at: Thu, 09 Feb 2017 22:34:38 UTC +00:00>]
     # ./spec/controllers/users_controller_spec.rb:49:in `block (2 levels) in <top (required)>'

  2) UsersController should only show public users on index
     Failure/Error: expect(assigns(:users)).to match_array([public_user, user])
     
       expected collection contained:  [#<User _id: BSON::ObjectId('589cee8272683d222a00001e'), admin: false, agree: nil, created_at: Thu, 0...lse, level: 0, mailing_list: false, sash_id: nil, updated_at: Thu, 09 Feb 2017 22:34:43 UTC +00:00>]
       actual collection contained:    [#<User _id: BSON::ObjectId('589ce8e872683d1223000000'), admin: true, agree: nil, created_at: Thu, 09...lse, level: 0, mailing_list: false, sash_id: nil, updated_at: Thu, 09 Feb 2017 22:34:43 UTC +00:00>]
       the extra elements were:        [#<User _id: BSON::ObjectId('589ce8e872683d1223000000'), admin: true, agree: nil, created_at: Thu, 09...lse, level: 0, mailing_list: false, sash_id: nil, updated_at: Thu, 09 Feb 2017 22:34:40 UTC +00:00>]
     # ./spec/controllers/users_controller_spec.rb:40:in `block (2 levels) in <top (required)>'

  3) Api::V1::TagsController lists tags
     Failure/Error: expect(json.length).to eq(2)
     
       expected: 2
            got: 6
     
       (compared using ==)
     # ./spec/controllers/api/api_tags_controller_spec.rb:16:in `block (2 levels) in <top (required)>'

  4) Api::V1::CropsController lists crops.
     Failure/Error: expect(json['data'].length).to eq(1)
     
       expected: 1
            got: 21
     
       (compared using ==)
     # ./spec/controllers/api/api_crops_controller_spec.rb:17:in `block (2 levels) in <top (required)>'

Finished in 7 minutes 3 seconds (files took 4.23 seconds to load)
114 examples, 4 failures, 7 pending

Failed examples:

rspec ./spec/controllers/users_controller_spec.rb:43 # UsersController should show all users on index if the current user is admin
rspec ./spec/controllers/users_controller_spec.rb:35 # UsersController should only show public users on index
rspec ./spec/controllers/api/api_tags_controller_spec.rb:13 # Api::V1::TagsController lists tags
rspec ./spec/controllers/api/api_crops_controller_spec.rb:14 # Api::V1::CropsController lists crops.
```

**Comment by RickCarlino** [comment]
Other errors have been removed for brevity.

**Comment by simonv3** [comment]
@RickCarlino You end up sorting this out?
